# Generated by Django 5.2.4 on 2025-07-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konditsioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('brand', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='default/cond.png', null=True, upload_to='kontitsionerlar/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
