# Generated by Django 5.2.4 on 2025-07-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_category_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
